ALTER TABLE documentos ADD COLUMN IF NOT EXISTS sha256 VARCHAR(64);
ALTER TABLE documentos ADD COLUMN IF NOT EXISTS version INTEGER NOT NULL DEFAULT 1;
ALTER TABLE documentos ADD COLUMN IF NOT EXISTS documento_origen_id BIGINT REFERENCES documentos(id) ON DELETE SET NULL;
ALTER TABLE documentos ADD COLUMN IF NOT EXISTS requiere_ocr BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE documentos ADD COLUMN IF NOT EXISTS confianza_extraccion NUMERIC(5,4);
CREATE INDEX IF NOT EXISTS documentos_sha256_idx ON documentos (causa_id, sha256);
