const { pool } = require("../configuracion/baseDatos");

async function enqueueDocumentJob(documentId, caseId, { force = false, type = "extraer_texto" } = {}) {
  if (!force) { const current = await pool.query("SELECT id FROM trabajos_documentales WHERE documento_id=$1 AND tipo=$2 AND estado IN ('pendiente','procesando') LIMIT 1", [documentId,type]); if (current.rowCount) return current.rows[0]; }
  const result = await pool.query(`INSERT INTO trabajos_documentales (documento_id,causa_id,tipo) VALUES ($1,$2,$3) RETURNING *`, [documentId,caseId,type]); return result.rows[0];
}
async function getDocumentJobs(documentId, caseId) { const result = await pool.query(`SELECT id,tipo,estado,intentos,max_intentos,progreso,error_codigo,error_detalle,iniciado_at,finalizado_at,created_at,updated_at FROM trabajos_documentales WHERE documento_id=$1 AND causa_id=$2 ORDER BY created_at DESC`, [documentId,caseId]); return result.rows; }
async function claimNextJob() {
  const client = await pool.connect();
  try { await client.query("BEGIN"); const result = await client.query(`SELECT t.*,d.nombre_archivo,d.mime_type,d.ruta_archivo,d.texto_extraido FROM trabajos_documentales t JOIN documentos d ON d.id=t.documento_id WHERE t.estado='pendiente' AND t.disponible_desde<=NOW() ORDER BY t.id FOR UPDATE OF t SKIP LOCKED LIMIT 1`);
    if (!result.rowCount) { await client.query("COMMIT"); return null; } const job=result.rows[0]; await client.query(`UPDATE trabajos_documentales SET estado='procesando',intentos=intentos+1,progreso=10,iniciado_at=NOW(),updated_at=NOW() WHERE id=$1`,[job.id]); if(job.tipo!=="indexar_rag")await client.query(`UPDATE documentos SET estado_procesamiento='procesando',updated_at=NOW() WHERE id=$1`,[job.documento_id]); await client.query("COMMIT"); return {...job,intentos:job.intentos+1};
  } catch(error){await client.query("ROLLBACK");throw error;} finally{client.release();}
}
async function completeJob(job, text) { const client=await pool.connect(); try { await client.query("BEGIN"); await client.query(`UPDATE documentos SET texto_extraido=$2,estado_procesamiento='texto_extraido',requiere_ocr=false,confianza_extraccion=1,updated_at=NOW() WHERE id=$1`,[job.documento_id,text]); await finishAndEnqueueIndex(client,job); await client.query("COMMIT"); } catch(error){await client.query("ROLLBACK");throw error;} finally{client.release();} }
async function failJob(job, error, { requiresOcr = false } = {}) { const final = requiresOcr || job.intentos >= job.max_intentos; const state=requiresOcr?'requiere_ocr':final?'error':'pendiente'; const delay=Math.min(300,2**job.intentos*5); await pool.query(`UPDATE trabajos_documentales SET estado=$2,progreso=$3,error_codigo=$4,error_detalle=$5,finalizado_at=CASE WHEN $6 THEN NOW() ELSE NULL END,disponible_desde=NOW()+($7||' seconds')::interval,updated_at=NOW() WHERE id=$1`,[job.id,state,final?100:0,requiresOcr?'OCR_REQUIRED':job.tipo==='indexar_rag'?'RAG_INDEX_ERROR':'EXTRACTION_ERROR',String(error.message||error).slice(0,1000),final||requiresOcr,delay]); if(job.tipo!=="indexar_rag")await pool.query(`UPDATE documentos SET estado_procesamiento=$2,requiere_ocr=$3,updated_at=NOW() WHERE id=$1`,[job.documento_id,requiresOcr?'requiere_ocr':final?'error':'pendiente',requiresOcr]); }
async function updateJobProgress(id,progress){await pool.query("UPDATE trabajos_documentales SET progreso=$2,updated_at=NOW() WHERE id=$1",[id,Math.max(1,Math.min(99,Math.round(progress)))]);}
async function completeOcrJob(job,result){const client=await pool.connect();try{await client.query("BEGIN");await client.query(`UPDATE documentos SET texto_extraido=$2,estado_procesamiento='texto_extraido',requiere_ocr=false,confianza_extraccion=$3,updated_at=NOW() WHERE id=$1`,[job.documento_id,result.text,result.confidence]);for(const page of result.pages){await client.query(`INSERT INTO paginas_documento(documento_id,numero,texto,confianza,metodo) VALUES($1,$2,$3,$4,'ocr') ON CONFLICT(documento_id,numero) DO UPDATE SET texto=EXCLUDED.texto,confianza=EXCLUDED.confianza,metodo='ocr',updated_at=NOW()`,[job.documento_id,page.number,page.text,page.confidence]);}await finishAndEnqueueIndex(client,job);await client.query("COMMIT");}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}}
async function finishAndEnqueueIndex(client,job){await client.query(`UPDATE trabajos_documentales SET estado='completado',progreso=100,finalizado_at=NOW(),error_codigo=NULL,error_detalle=NULL,updated_at=NOW() WHERE id=$1`,[job.id]);await client.query(`INSERT INTO trabajos_documentales(documento_id,causa_id,tipo) SELECT $1,$2,'indexar_rag' WHERE NOT EXISTS(SELECT 1 FROM trabajos_documentales WHERE documento_id=$1 AND tipo='indexar_rag' AND estado IN('pendiente','procesando'))`,[job.documento_id,job.causa_id]);}
async function completeIndexJob(job){await pool.query(`UPDATE trabajos_documentales SET estado='completado',progreso=100,finalizado_at=NOW(),error_codigo=NULL,error_detalle=NULL,updated_at=NOW() WHERE id=$1`,[job.id]);}
module.exports={claimNextJob,completeJob,completeIndexJob,completeOcrJob,enqueueDocumentJob,failJob,getDocumentJobs,updateJobProgress};
